- name: Launch ec2 instance
  ec2:
    key_name: TESTING
    instance_type: t2.micro
    image: ami-0ebc1ac48dfd14136
    wait: yes
    instance_tags:
      name: web
    group: httpWebServer
    count: 1
    vpc_subnet_id: subnet-bbf5cfd3
    region: ap-south-1 
    assign_public_ip: yes
