- name: launch ec2 instance
  hosts: localhost
  tasks:
  - name: create a new ec2 key pair, returns generated private key
    ec2_key:
       name: my_keypair
    register: ec2_key_result

  - name: save private key
    copy: content="{{ ec2_key_result.key.private_key }}" dest="my_keypair.pem" mode=0600
    when: ec2_key_result.changed 

  - name: Launch ec2 instance
    ec2:
      key_name: my_keypair 
      instance_type: t2.micro
      image: ami-0ebc1ac48dfd14136
      wait: yes
      instance_tags:
        name: web
      group: httpWebServer
      count: 1
      vpc_subnet_id: subnet-bbf5cfd3
      region: ap-south-1 
      assign_public_ip: yes
